### ISSUE TITLE
Update Local IP interface in conkyrc3

### ISSUE THREAD

**Issue by RedAtRareCandy** [luizfnunes/SingleCOne-Conky#2]
Hi,

When using Conky Manager's Edit Widget dialog, under the Network tab it permits the changing of the Interface (default lo), however when updated it will only update the Up Speed and Down Speed lines in the conkyrc3 file.
Should it also be updating the Local IP line also? That remains as lo (127.0.0.1) and needs to be manually updated to reflect true local IP address.

**Comment by luizfnunes** [comment]
Hi.
Unfortunately the Conky Manager does not update the command "addr" of conky, used to display the local ip, the change needs to be performed manually.
